version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_apiprodutos
    environment:
      POSTGRES_DB: apiprodutos
      POSTGRES_USER: apiprodutos
      POSTGRES_PASSWORD: apiprodutos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 